[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "llm-testbed"
version = "0.1.0"
description = "Modular LLM Security Testbed"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "httpx",
    "pydantic",
    "streamlit",
    "python-dotenv",
    "langfuse",
    "pytest",
    "pytest-asyncio",
    "respx",
    "watchdog",
    "scikit-learn",
    "rapidfuzz",
    "joblib"
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
asyncio_mode = "auto"
